### ISSUE TITLE
sql issue on hits.php

### ISSUE THREAD

**Issue by danmarsden** [marceloschmitt/moodle-block_analytics_graphs#1]
Debug info: ERROR: column "log.id" must appear in the GROUP BY clause or be used in an aggregate function
LINE 4: SELECT log.id, log.userid, firstname, la...
^
SELECT id, userid, firstname, lastname, email, week, COUNT(_) as number,
SUM(numberofpageviews) as numberofpageviews
FROM (
SELECT log.id, log.userid, firstname, lastname, email,
FLOOR((log.timecreated + $1) / 86400) as day,
FLOOR( (((log.timecreated + $2) / 86400) - ($3/86400))/7) as week,
COUNT(_) as numberofpageviews
FROM mdl_logstore_standard_log as log
LEFT JOIN mdl_user usr ON usr.id = log.userid
WHERE courseid = $4 AND action = 'viewed' AND target = 'course' AND log.timecreated >= $5 AND log.userid = $6
GROUP BY userid, day
) as temp
GROUP BY userid, week
ORDER BY LOWER(firstname), LOWER(lastname),userid, week
[array (
0 => 356400,
1 => 356400,
2 => '1405602000',
3 => 2,
4 => '1405602000',
5 => '2',
)]
Error code: dmlreadexception
Stack trace:
line 443 of /lib/dml/moodle_database.php: dml_read_exception thrown
line 244 of /lib/dml/pgsql_native_moodle_database.php: call to moodle_database->query_end()
line 764 of /lib/dml/pgsql_native_moodle_database.php: call to pgsql_native_moodle_database->query_end()
line 142 of /blocks/analytics_graphs/lib.php: call to pgsql_native_moodle_database->get_records_sql()
line 48 of /blocks/analytics_graphs/hits.php: call to block_analytics_graphs_get_number_of_days_access_by_week()

**Comment by marceloschmitt** [comment]
Ok, Dan. I have payed so much attention to the other GROUP BY problem we were discussing that forgot this one. Ridiculous.

**Comment by danmarsden** [comment]
hehe - you should see the results of some of my testing.... :-)

**Comment by danmarsden** [comment]
(as in the same mistakes I've made time and time again.....)

**Comment by mudrd8mz** [comment]
I can still reproduce this with the most recent version available in the Plugins directory https://moodle.org/plugins/pluginversion.php?id=8107

**Comment by danmarsden** [comment]
I've just tested your latest code on my postgres install and found a couple more sql issues - I've just filed a pull request with some fixes that worked on my install - the graphs look really cool - nice work!

Hopefully the patches make sense (and don't break anything on mysql)

**Comment by marceloschmitt** [comment]
Will upload the new version and ask for test again in moodle repository.
