### ISSUE TITLE
missing string

### ISSUE THREAD

**Issue by ak4t0sh** [marceloschmitt/moodle-block_analytics_graphs#11]
`$string['analytics_graphs:bemonitored']` is missing into your languages files.

**Comment by marceloschmitt** [comment]
Where is it used? And which version are you using?

**Comment by ak4t0sh** [comment]
It is a permission defined here [db/access.php#18](https://github.com/marceloschmitt/moodle-block_analytics_graphs/blob/315734932925b781849a6bec05f5be6e6d26a8cf/db/access.php#L18) and used into [lib.php#57](https://github.com/marceloschmitt/moodle-block_analytics_graphs/blob/315734932925b781849a6bec05f5be6e6d26a8cf/lib.php#L57)

**Comment by marceloschmitt** [comment]
Ok. Now I got it. It is not something that appears when using the block. The thing is in administration of the roles. I will fix it. Thank you very much.

**Comment by marceloschmitt** [comment]
Fixed in version 3.0.
