### ISSUE TITLE
Missing capability myaddinstance

### ISSUE THREAD

**Issue by kkiiskin** [marceloschmitt/moodle-block_analytics_graphs#12]
Moodle 3.1 gives a notice:

"The block analytics_graphs does not define the standard capability block/analytics_graphs:myaddinstance"

**Comment by marceloschmitt** [comment]
When does it gives that notice?

**Comment by ewallah** [comment]
my  page

The block analytics_graphs does not define the standard capability block/analytics_graphs:myaddinstance
line 595 of /blocks/moodleblock.class.php: call to debugging()
line 567 of /blocks/moodleblock.class.php: call to block_base->has_add_block_capability()
line 228 of /lib/blocklib.php: call to block_base->user_can_addto()
line 2229 of /lib/blocklib.php: call to block_manager->get_addable_blocks()
line 1252 of /lib/blocklib.php: call to block_add_block_ui()
line 579 of /lib/outputrenderers.php: call to block_manager->ensure_content_created()
line 39 of /theme/bootstrapbase/renderers/core_renderer.php: call to core_renderer->standard_head_html()
line 27 of /theme/???/layout/columns3.php: call to theme_bootstrapbase_core_renderer->standard_head_html()
line 1162 of /lib/outputrenderers.php: call to include()
line 1092 of /lib/outputrenderers.php: call to core_renderer->render_page_layout()
line 164 of /my/index.php: call to core_renderer->header()

**Comment by uditniec** [comment]
Hi, how to fix this error? I also facing this.. Please help.

**Comment by marceloschmitt** [comment]
Sorry. I was really busy. I am back. This afternoon I will dedicate myself to that issue.

**Comment by ewallah** [comment]
add this to db/access.php
    'block/analytics_graphs:myaddinstance' => array(
        'riskbitmask' => RISK_SPAM | RISK_XSS,
        'captype' => 'write',
        'contextlevel' => CONTEXT_BLOCK,
        'archetypes' => array(
            'editingteacher' => CAP_ALLOW,
            'manager' => CAP_ALLOW
        ),
        'clonepermissionsfrom' => 'moodle/site:manageblocks'
    ),
The language string is already there, so no need to add 
$string['analytics_graphs:myaddinstance'] = 'Add a new AG block to the My Moodle page';

**Comment by marceloschmitt** [comment]
Doing that now with another correction.

Marcelo A. Rauh Schmitt
marcelo.schmitt@poa.ifrs.edu.br
Diretor geral do Campus Porto Alegre
Instituto Federal do Rio Grande do Sul (IFRS)



> Em 18 de jun de 2018, à(s) 10:04, ewallah <notifications@github.com> escreveu:
> 
> 'block/analytics_graphs:myaddinstance' => array(
> 'riskbitmask' => RISK_SPAM | RISK_XSS,
> 'captype' => 'write',
> 'contextlevel' => CONTEXT_BLOCK,
> 'archetypes' => array(
> 'editingteacher' => CAP_ALLOW,
> 'manager' => CAP_ALLOW
> ),
> 'clonepermissionsfrom' => 'moodle/site:manageblocks'
> ),

**Comment by marceloschmitt** [comment]
Done and published

Marcelo A. Rauh Schmitt
marcelo.schmitt@poa.ifrs.edu.br
Diretor geral do Campus Porto Alegre
Instituto Federal do Rio Grande do Sul (IFRS)



> Em 25 de jul de 2018, à(s) 11:12, Marcelo Augusto Rauh Schmitt <marcelo.schmitt@poa.ifrs.edu.br> escreveu:
> 
> Doing that now with another correction.
> 
> Marcelo A. Rauh Schmitt
> marcelo.schmitt@poa.ifrs.edu.br <mailto:marcelo.schmitt@poa.ifrs.edu.br>
> Diretor geral do Campus Porto Alegre
> Instituto Federal do Rio Grande do Sul (IFRS)
> 
> 
> 
>> Em 18 de jun de 2018, à(s) 10:04, ewallah <notifications@github.com <mailto:notifications@github.com>> escreveu:
>> 
>> 'block/analytics_graphs:myaddinstance' => array(
>> 'riskbitmask' => RISK_SPAM | RISK_XSS,
>> 'captype' => 'write',
>> 'contextlevel' => CONTEXT_BLOCK,
>> 'archetypes' => array(
>> 'editingteacher' => CAP_ALLOW,
>> 'manager' => CAP_ALLOW
>> ),
>> 'clonepermissionsfrom' => 'moodle/site:manageblocks'
>> ),
>
