### ISSUE TITLE
Timezone function is depricated

### ISSUE THREAD

**Issue by elliott2081** [marceloschmitt/moodle-block_analytics_graphs#13]
Test Grade Patch
Coding error detected, it must be fixed by a programmer: get_user_timezone_offset() can not be used any more, please use standard PHP DateTimeZone class instead

More information about this error

Debug info: 
Error code: codingerror
Stack trace:
line 2161 of /lib/deprecatedlib.php: coding_exception thrown
line 272 of /blocks/analytics_graphs/lib.php: call to get_user_timezone_offset()
line 66 of /blocks/analytics_graphs/hits.php: call to block_analytics_graphs_get_number_of_modules_access_by_week()

**Comment by marceloschmitt** [comment]
Thanks a lot. I fixed the code. It is in version 3.0 now.

**Comment by elliott2081** [comment]
Thank you! Wasn't exactly sure how to replace it.

**Comment by marceloschmitt** [comment]
If anything goes wrong, let me know.

Marcelo A. Rauh Schmitt
marcelo.schmitt@poa.ifrs.edu.br
Diretor geral do Campus Porto Alegre
Instituto Federal do Rio Grande do Sul (IFRS)

> Em 1 de set de 2016, à(s) 12:03, David Elliott notifications@github.com escreveu:
> 
> Thank you! Wasn't exactly sure how to replace it. 
> 
> Sent from my mobile 
>
