### ISSUE TITLE
Problems with groups

### ISSUE THREAD

**Issue by benchen71** [marceloschmitt/moodle-block_analytics_graphs#28]
I am having a problem when changing from "show all groups" mode to a group.

Here's a section of the course in "show all groups" mode.  All of the items (when you add the number of students who accessed the item to the number who didn't) correctly add up to 28:
![image 001](https://user-images.githubusercontent.com/6054381/32261417-7965b5aa-bf22-11e7-9d8e-049710ce5ed4.png)

However, when I change to a group, some of the items correctly add up to 9, but not all.  Some show a higher combined total:
![image 002](https://user-images.githubusercontent.com/6054381/32261462-c2bfbaca-bf22-11e7-849a-6e71f963c076.png)

I think the numbers for student accesses are correct.  But the non access numbers are wrong: and when you click the red bars, there is no associated user information:
![image 003](https://user-images.githubusercontent.com/6054381/32261497-fe0570d4-bf22-11e7-8b94-78de7d758496.png)

In this image, there is one student correctly in the non access group, but three "phantom" students:
![image 004](https://user-images.githubusercontent.com/6054381/32261551-6b51ee88-bf23-11e7-991d-1c491b79cd51.png)

Anyone else experiencing this issue?

**Comment by marceloschmitt** [comment]
Strange. Thanks a lot. Would allow me to see it? Would transform me in a teacher inside the course? My email is marcelo.schmitt@poa.ifrs.edu.br. There must be a code error, but never happened to me.

**Comment by benchen71** [comment]
I have a fix for this bug in Pull Request #29.

**Comment by marceloschmitt** [comment]
Thank you, Ben. I will merge now.
