### ISSUE TITLE
debugging messages on assign.php

### ISSUE THREAD

**Issue by danmarsden** [marceloschmitt/moodle-block_analytics_graphs#3]
get_context_instance() is deprecated, please use context_xxxx::instance() instead.
line 3237 of /lib/deprecatedlib.php: call to debugging()
line 32 of /blocks/analytics_graphs/graphDateOfAccess.php: call to get_context_instance()
line 23 of /blocks/analytics_graphs/assign.php: call to graphDateOfAccess->__construct()
Invalid get_string() identifier: 'title_one' or component 'block_analytics_graphs'. Perhaps you are missing $string['title_one'] = ''; in /var/www/moodle-r2/blocks/analytics_graphs/lang/en/block_analytics_graphs.php?
line 348 of /lib/classes/string_manager_standard.php: call to debugging()
line 6959 of /lib/moodlelib.php: call to core_string_manager_standard->get_string()
line 24 of /blocks/analytics_graphs/assign.php: call to get_string()
get_context_instance() is deprecated, please use context_xxxx::instance() instead.
line 3237 of /lib/deprecatedlib.php: call to debugging()
line 36 of /blocks/analytics_graphs/lib.php: call to get_context_instance()
line 51 of /blocks/analytics_graphs/graphDateOfAccess.php: call to block_analytics_graphs_get_students()
line 26 of /blocks/analytics_graphs/assign.php: call to graphDateOfAccess->create_graph()
get_role_users() without specifying one single roleid needs to be called prefixing role assignments id (ra.id) as unique field, you can use $fields param for it.
line 4091 of /lib/accesslib.php: call to debugging()
line 38 of /blocks/analytics_graphs/lib.php: call to get_role_users()
line 51 of /blocks/analytics_graphs/graphDateOfAccess.php: call to block_analytics_graphs_get_students()
line 26 of /blocks/analytics_graphs/assign.php: call to graphDateOfAccess->create_graph()

Notice: Undefined variable: resultado in /var/www/moodle-r2/blocks/analytics_graphs/lib.php on line 31
Unknown table specified in objecttable field
line 673 of /lib/classes/event/base.php: call to debugging()
line 695 of /lib/classes/event/base.php: call to core\event\base->validate_before_trigger()
line 181 of /blocks/analytics_graphs/graphDateOfAccess.php: call to core\event\base->trigger()
line 26 of /blocks/analytics_graphs/assign.php: call to graphDateOfAccess->create_graph()

**Comment by marceloschmitt** [comment]
Corrected warnings related to get_role_users() , objecttable and unexpected char. Will leave get_context_instance for compatibility reasons. Will create another branch for newer version of Moodle.

**Comment by danmarsden** [comment]
those warnings won't block your plugin from being accepted - just let me know when you're ready for me to re-test the sql stuff :-)

**Comment by marceloschmitt** [comment]
I am ready. I have already asked that in moodle.org.

**Comment by danmarsden** [comment]
sorry, missed that! - I think there are still possibly a few issues with the group by aggregates used when looking at the code here in github but I think you've done enough work so far to justify making the plugin public.

**Comment by marceloschmitt** [comment]
Dan
I will adjust that. I may use the weekend. Don't worry. And if you want to wait for approval, it is ok.

**Comment by marceloschmitt** [comment]
Decided to use context new function and make it compatible to Moodle 2.2 on.
