### ISSUE TITLE
Can it be?

### ISSUE THREAD

**Issue by dinism** [marceloschmitt/moodle-block_analytics_graphs#31]
![imagem](https://user-images.githubusercontent.com/14828021/35411238-f0efb3ca-020f-11e8-83b1-2a44510fd24e.png)

**Comment by marceloschmitt** [comment]
Dinis

Para português? A tela da esquerda, sim. Foi um esquecimento. A da direita, vou ter de olhar o Highcharts. Não é o meu software que gera.

**Comment by dinism** [comment]
OBRIGADO

**Comment by marceloschmitt** [comment]
Dinis

A tua solicitação do lado esquerdo está feita. Vou olhar depois a questão do download. Por enquanto, consegues baixar a versão nova com "git pull". Assim que eu fizer os outros ajustes pedidos por outros usuários, eu crio uma nova release.

**Comment by Jarvil** [comment]
Hello,

Where can you translate these from?

**Comment by marceloschmitt** [comment]
What do you want to translate Jarvil?

**Comment by Jarvil** [comment]
Hello,

Text like "Print chart", "download PNG image", "download PDF Document" etc.

![print](https://user-images.githubusercontent.com/15193418/50625780-e2d67e00-0f32-11e9-8aec-5c104b4fea9c.png)

**Comment by marceloschmitt** [comment]
Jarvil, I am back. 
That text belongs to a software that I use to support the graphics: high slide. I found some instructions here: https://localize.drupal.org/translate/downloads?project=highslide
