### ISSUE TITLE
Groups access control

### ISSUE THREAD

**Issue by senaiboy** [marceloschmitt/moodle-block_analytics_graphs#32]
"Separate groups" is set for course and activities.
Teacher's permission for _moodle/site:accessallgroups_ is set to "Prohibit".

When a teacher is accessing these graphs, they are still able to see other groups (not just their own group). Is this a known issue?

**Comment by wbuk** [comment]
We have tried to use this on our site and it has 3 schools using it.  Due to grouping access control missing, every school can see each others students graphs, so we have had to remove it for now.  Please, can you add Group Access Control  Thank you so much.

**Comment by marceloschmitt** [comment]
Senaiboy

It was not known. I will try to fix it.

Wbuk, I will try to fix it.

**Comment by senaiboy** [comment]
Hi Marcelo, sorry to bother, is there any progress on this issue? Is there any way we could help with it?

This is a fantastic plugin but currently we can't use it due to GDPR (data accessible by users that shouldn't have access).

**Comment by marceloschmitt** [comment]
I am sorry. I was really busy. This afternoon I will do something about it.

**Comment by marceloschmitt** [comment]
Ok. It is fixed. If you make a git pull, it must work. I will probably generate a new release also. Sorry for taking so long.
