### ISSUE TITLE
Request Time Out 

### ISSUE THREAD

**Issue by MrOli3000** [marceloschmitt/moodle-block_analytics_graphs#34]
After about 3 minutes im getting the error:

"This request takes too long to process. It is timed out by the server. Please contact the administrator of this web site to increase "Connections Timeout".

I was running fine previously but now even very small reports that span a day are timing out. 

We have many activities in our courses. Could it be related to that?

**Comment by marceloschmitt** [comment]
It is strange. Nothing has been changed. The more activities you have, the more time it takes to execute. But the message is strange. It should be a message like:

Fatal error: Maximum execution time of n seconds exceeded in
