### ISSUE TITLE
no module was access until now doesn't work right?

### ISSUE THREAD

**Issue by Jarvil** [marceloschmitt/moodle-block_analytics_graphs#35]
Hello,

How can I have a student "Moodletuki4 Oppilasrooli4" with yellow triangle with message **"no module was access until now"** on "Hits distribution" page while he has in "content access" -tab Access percentage of 2.6%.

Also "hits distribution" page shows he has 0 accessed resources.

![cont1](https://user-images.githubusercontent.com/15193418/50626977-0fda5f00-0f3a-11e9-8a05-599bdc455a46.png)

![cont2](https://user-images.githubusercontent.com/15193418/50626981-149f1300-0f3a-11e9-8014-32e208c112dd.png)

**Comment by Jarvil** [comment]
Are content, module and resource access three separate things? If so how are they specified?

**Comment by jarvil1** [comment]
Hello,

I'm sorry I must have missed your answer, is this a bug or not?

**Comment by marceloschmitt** [comment]
Content, module and resource are three separate things.

**Comment by marceloschmitt** [comment]
Ok. Let me see. 
The query is this:

SELECT userid+(week*1000000), userid, firstname, lastname, email, week, number
                FROM (
                    SELECT  userid, week, COUNT(*) as number
                    FROM (
                        SELECT log.userid, objecttable, objectid,
                        FLOOR((((log.timecreated + ?) / 86400) - (?/86400))/7) as week
                        FROM {logstore_standard_log} log
                        WHERE courseid = ? AND action = 'viewed' AND target = 'course_module'
                        AND log.timecreated >= ? AND log.userid $insql
                        GROUP BY userid, week, objecttable, objectid
                    ) as temp
                    GROUP BY userid, week
                ) as temp2
                LEFT JOIN {user} usr ON usr.id = temp2.userid
                ORDER by LOWER(firstname), LOWER(lastname), userid, week


action = 'viewed' AND target = 'course_module' - parameters to select from log table.

So, it is everything that was accessed in the course. They are all the same. It means that you discover something to fix in the context of the interface.
