### ISSUE TITLE
Moodle 3.6 & 3.9 support?

### ISSUE THREAD

**Issue by jarvil1** [marceloschmitt/moodle-block_analytics_graphs#38]
Hello,

Will this plugin support Moodle 3.6 & 3.9?

**Comment by marceloschmitt** [comment]
Yes. Actually, I tested and it is working.

**Comment by jarvil1** [comment]
Hello,

When is 3.9 version going to released on 

https://moodle.org/plugins/block_analytics_graphs

**Comment by iqbaljaiz** [comment]
Is this plugin supported in moodle version 3.10?

**Comment by marceloschmitt** [comment]
Yes it is.
