### ISSUE TITLE
Viewing analytics for all who attempted quiz

### ISSUE THREAD

**Issue by ellicetannnn** [marceloschmitt/moodle-block_analytics_graphs#40]
Hello! I would like to ask if there is a way for only the admin/teachers to view the analytics for the quiz by **all** students? Currently I (an admin) can only view the analytics of my attempt but not the students which is what I want.

**Comment by marceloschmitt** [comment]
As a teacher, you should see all students in the plugin. Can you send me a screenshot? You can use my email: marcelo.schmitt@poa.ifrs.edu.br.

**Comment by ellicetannnn** [comment]
I haven sent the screenshot to your email, do help me out! Thank you very much.

**Comment by ellicetannnn** [comment]
My deepest apologies, I got confused with the different plugins and I'm a beginner here. I was intending to use yours and have it installed on my moodle. Is there a particular setting to navigate to the charts? Or will it just appear under the "Grades" section for the teacher? I'll  lose the issue on github. Once again, sorry for being mistaken.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by marceloschmitt** [comment]
You can access my plugin in two ways: with the block that is installed (usually right side) or in Reports clicking in AnalyticsGraphs.

Marcelo Augusto Rauh Schmitt
marcelo.schmitt@poa.ifrs.edu.br
