### ISSUE TITLE
Error accessing the logs 

### ISSUE THREAD

**Issue by izendegi** [marceloschmitt/moodle-block_analytics_graphs#41]
Just acknowledging that there is an issue with this plugin when accesing the course logs on Moodle 3.11:

https://moodle.org/mod/forum/discuss.php?d=423173

I've experienced it and as a workaround I have tried to disable the block but it hasn't solved it, so I've uninstalled the block.

**Comment by marceloschmitt** [comment]
I have a new version. I will test this issue before publishing it. I hope you can help me solve it.

Marcelo Augusto Rauh Schmitt
***@***.***

**Comment by izendegi** [comment]
Sure, tell me when it's ready and I'll test it.

**Comment by izendegi** [comment]
I've seen you've published a new version of the plugin at moodle.org and tried to install it but I get this error:

syntax error, unexpected '$plugin' (T_VARIABLE) Debug: 
Error code: generalexceptionmessage
* line 24 of /blocks/analytics_graphs/version.php: ParseError thrown
* line 1104 of /lib/classes/component.php: call to core_component::get_all_versions()
* line 8104 of /lib/moodlelib.php: call to core_component::get_all_versions_hash()
* line 60 of /index.php: call to moodle_needs_upgrading()

**Comment by marceloschmitt** [comment]
I make a mistake with the releases version. Ridiculous. Sorry. Fixed.

**Comment by izendegi** [comment]
Yes, with the new version I can install the plugin correctly, but when doing it the error with the log report happens again so it seems like the original issue isn't fixed yet. :-(

**Comment by marceloschmitt** [comment]
Ok, Izendigi. Let's solve it now, ok? Tell me exactly what happens. You installed the new plugin. Then in what situation the error occurs? Can you talk to me using marcelo.schmit@poa.ifrs.edu.br? It may be faster to solve the issue.

**Comment by izendegi** [comment]
To reproduce the issue, once the block is installed, I just have to navigate to one course's activity log report (doesn't matter if the course has the block added or not):
yourmoodleurl.org/report/log/index.php?id=99999

https://docs.moodle.org/311/en/Logs#Logs_of_course_activity

Doing that the report doesn't show up, and instead of that I get this message:
Exception - Call to a member function out() on null

And I've found this message on the PHP log:
Error code: generalexceptionmessage
* line 54 of /lib/classes/report_helper.php: Error thrown
* line 196 of /report/log/index.php: call to core\report_helper::print_report_selector()

P.S.: I've tried to send this by email but the mail server answered that the email account does not exist

**Comment by marceloschmitt** [comment]
I think it is ok now in 4.2.1 release. 
Thanks.

**Comment by izendegi** [comment]
Yes, the issue is gone on 4.2.1, thank you @marceloschmitt
