### ISSUE TITLE
Error code: generalexceptionmessage 

### ISSUE THREAD

**Issue by caiadogithub** [marceloschmitt/moodle-block_analytics_graphs#42]
Analytics graphs v4.2.0 (2021090601)
Moodle 3.10.6+
PostgreSQL 12
Ubuntu 20.04
PHP 7.4

Exception - syntax error, unexpected '$plugin' (T_VARIABLE)

Stack trace:

    line 24 of /blocks/analytics_graphs/version.php: ParseError thrown
    line 1104 of /lib/classes/component.php: call to core_component::get_all_versions()
    line 8255 of /lib/moodlelib.php: call to core_component::get_all_versions_hash()
    line 535 of /admin/index.php: call to moodle_needs_upgrading()

**Comment by marceloschmitt** [comment]
I am really sorry. I changed the name of the release here and did not synchronised in my notebook. It was ridiculous. Fixed it.

Marcelo
