### ISSUE TITLE
Missing thirdpartylibs.xml file

### ISSUE THREAD

**Issue by danmarsden** [marceloschmitt/moodle-block_analytics_graphs#43]
When including an external library in your plugin, you must include a thirdpartylibs.xml file that includes the name, location and license of the library.
More information on this is here:
https://docs.moodle.org/dev/Plugin_files#thirdpartylibs.xml
And here:
https://docs.moodle.org/dev/Plugin_with_third_party_libraries

One of the other advantages of using this is that Moodle's codechecker automatically ignores any files included in the location specificed in the thirdpartylibs.xml file.

Please note - this is typically a blocker for new plugins submission to the plugins db so it would be really good to get fixed! :-)

**Comment by marceloschmitt** [comment]
Done.
