### ISSUE TITLE
failing privacy api tests

### ISSUE THREAD

**Issue by danmarsden** [marceloschmitt/moodle-block_analytics_graphs#45]
1) provider_testcase::test_all_providers_compliant with data set "block_analytics_graphs" ('block_analytics_graphs', 'block_analytics_graphs\privac...ovider')
Failed asserting that false is true.

/var/www/html/privacy/tests/provider_test.php:178
/var/www/html/lib/phpunit/classes/advanced_testcase.php:80

To re-run:
 vendor/bin/phpunit --colors "provider_testcase" privacy/tests/provider_test.php

2) provider_testcase::test_table_coverage
The following tables with user fields must be covered with metadata providers: 
  - block_analytics_graphs_msg (fromid)
  - block_analytics_graphs_dest (toid)

**Comment by dmitriim** [comment]
I have fixed that. Please have a look at https://github.com/marceloschmitt/moodle-block_analytics_graphs/pull/50
