### ISSUE TITLE
"LOG" table as parameter

### ISSUE THREAD

**Issue by mglaredo** [marceloschmitt/moodle-block_analytics_graphs#48]
I've recently found this amazing plugin and just started to studied it. 

My first contribution (from a medium-high size University) is to say that, on certain circumstances, using directly the "live" Log Table could become an scaling problem. One possible workaround for Moodle Architect and Administrator would be to have log_table on the plugin config and therefore more flexibility to fight against performance issues. Another improvement would be combining summarized data obtained periodically and customizable by Scheduled tasks.

**Comment by marceloschmitt** [comment]
Yes. The best approach would be to use another database. That is a main change in the system. Something for the long future.
