### ISSUE TITLE
Error messages when accessing dashboard in editing mode

### ISSUE THREAD

**Issue by bongodoctor** [marceloschmitt/moodle-block_analytics_graphs#49]
Plugin works fine, but we are getting the following error if we visit the dashboard page in editing mode:

The block analytics_graphs does not define the standard capability block/analytics_graphs:myaddinstance
line 651 of \blocks\moodleblock.class.php: call to debugging()
line 617 of \blocks\moodleblock.class.php: call to block_base->has_add_block_capability()
line 228 of \lib\blocklib.php: call to block_base->user_can_addto()
line 2274 of \lib\blocklib.php: call to block_manager->get_addable_blocks()
line 1242 of \lib\blocklib.php: call to block_add_block_ui()
line 647 of \lib\outputrenderers.php: call to block_manager->ensure_content_created()
line 45 of \theme\mb2nl\renderers\core.php: call to core_renderer->standard_head_html()
line 57 of \theme\mb2nl\layout\parts\head.php: call to theme_mb2nl_core_renderer->standard_head_html()
line 104 of \theme\mb2nl\renderers\core.php: call to include()
line 86 of \theme\mb2nl\layout\columns3.php: call to theme_mb2nl_core_renderer->theme_part()
line 1400 of \lib\outputrenderers.php: call to include()
line 1330 of \lib\outputrenderers.php: call to core_renderer->render_page_layout()
line 165 of \my\index.php: call to core_renderer->header()

**Comment by bongodoctor** [comment]
This is on Moodle 3.11.6+ (Build: 20220325) | Version 2021051706.04 | Stable version |

**Comment by dmitriim** [comment]
Please have a look at https://github.com/marceloschmitt/moodle-block_analytics_graphs/pull/51

**Comment by marceloschmitt** [comment]
The code is merged.

**Comment by bongodoctor** [comment]
Thanks will check it out :)
