### ISSUE TITLE
Multiple issues with email.php

### ISSUE THREAD

**Issue by mudrd8mz** [marceloschmitt/moodle-block_analytics_graphs#9]
The functionality does not work to me, throwing SQL error. Trying to debug led me to your lib.php where `get_role_users()` has hardcoded list of role IDs. That is wrong. You must not rely on particular record IDs.

**Comment by marceloschmitt** [comment]
David
I suppose you are talking about line 61, where I kept ids 35 and 36, aren't you? That was I test I will correct. But there is another issue. Can I consider that students will always have id number 5, or should I first discover the id of student role.

**Comment by mudrd8mz** [comment]
You must never rely on any particular ID. In fact, you should never check for roles. Always check for capabilities.

**Comment by marceloschmitt** [comment]
I see, but I must generate the graphs for the every student and not for every one who is able to view the course. At least in line 53. 

In line 60, I do have an error. I must discover who has capabilities related to the block in order to send a copy of the email.

**Comment by mudrd8mz** [comment]
> I must generate the graphs for the every student

Right. The conceptually correct approach is to define a new capability, something like "be monitored" or so. By default, this capability should be allowed to the student archetype. To get the list of users who should be displayed in the graph, you would then probably use `get_enrolled_users()` or `get_enrolled_sql()` with the second argument provided.

**Comment by marceloschmitt** [comment]
Thank you.

**Comment by marceloschmitt** [comment]
Solution for the issue:

$capabilities = array(
    'block/analytics_graphs:bemonitored' => array(
        'captype' => 'read',
        'contextlevel' => CONTEXT_BLOCK,
        'archetypes' => array(
            'student' => CAP_ALLOW,
        )
    ),

function block_analytics_graphs_get_students($course) {
    $students = array();
    $context = context_course::instance($course);
    $allstudents = get_enrolled_users($context, 'block/analytics_graphs:bemonitored', 0,
                    'u.id, u.firstname, u.lastname, u.email, u.suspended', 'firstname, lastname');
    foreach($allstudents as $student) {
        if($student->suspended == 0) {
            $students[] = $student;
        }
    }
    return($students);
}

function block_analytics_graphs_get_teachers($course) {
    $teachers = array();
    $context = context_course::instance($course);
    $allteachers = get_enrolled_users($context, 'block/analytics_graphs:viewpages', 0,
                    'u.id, u.firstname, u.lastname, u.email, u.suspended', 'firstname, lastname');
    foreach($allteachers as $teacher) {
        if($teacher->suspended == 0) {
            $teachers[] = $teacher;
        }
    }
    return($teachers);
}

**Comment by mudrd8mz** [comment]
Yup, this is the way to go. As you can realize, it is much more flexible, too - especially in courses that do not use standard roles or need more detailed configuration.
